# Generated by Django 3.1.1 on 2020-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
